language: python
python:
  - "3.7"

# command to install dependencies
install:
  - pip install pandas==0.25.2
  - pip install numpy
  - pip install sympy
  - pip install shapely
  - pip install xlsxwriter
  - pip install xlrd
#  - pip install psycopg2-binaryyam
  - pip install psycopg2==2.7.5
  - pip install sqlalchemy
  - pip install pytest

env:
  global:
    - LANDBOSSE_INPUT_DIR: $TRAVIS_BUILD_DIR/project_input_template
    - LANDBOSSE_OUTPUT_DIR: $TRAVIS_BUILD_DIR/project_input_template

# command to run tests
script:
  - pytest $TRAVIS_BUILD_DIR/landbosse/landbosse_api/API_test/API_test.py
  - python $TRAVIS_BUILD_DIR/main.py --validate

branches:
  only:
    - pip_installable
    - develop
