name: CI_LandBOSSE

# We run CI on push commits and pull requests on all branches
on: [push, pull_request]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
    build_pip:
        name: Pip Build (${{ matrix.os }})
        runs-on: ${{ matrix.os }}
        strategy:
            fail-fast: False
            matrix:
                os: ["ubuntu-latest", "windows-latest"]
                python-version: [3.6, 3.7, 3.8]

        steps:
            - uses: actions/checkout@v2
            - name: Set up Python ${{ matrix.python-version }}
              uses: actions/setup-python@v2
              with:
                  python-version: ${{ matrix.python-version }}
                
            - name: Pip Install Dependencies
              shell: pwsh
              run: |
                  python -m pip install --upgrade pip install pytest pandas numpy scipy xlsxwriter openpyxl openmdao

            - name: Pip Install LandBOSSE
              shell: pwsh
              run: |
                  pip install -e .

            # Validate
            - name: Pip Validation
              shell: pwsh
              run: |
                  python main.py --input project_input_template --output project_input_template --validate

            # Run tests
            - name: Pip Run pytest
              shell: pwsh
              run: |
                  pytest landbosse/tests


    build_conda:
        name: Conda Build (${{ matrix.os }})
        runs-on: ${{ matrix.os }}
        strategy:
            fail-fast: False
            matrix:
                os: ["ubuntu-latest", "windows-latest"]
                python-version: [3.8]

        steps:
            - uses: actions/checkout@v2
            - uses: conda-incubator/setup-miniconda@v2
              # https://github.com/marketplace/actions/setup-miniconda
              with:
                  miniconda-version: "latest"
                  auto-update-conda: true
                  python-version: 3.8
                  environment-file: environment.yml

            # Install 
            - name: Conda Install LandBOSSE
              shell: pwsh
              run: |
                  python setup.py develop

            # Validate
            - name: Conda Validation
              shell: pwsh
              run: |
                  python main.py --input project_input_template --output project_input_template --validate

            # Run tests
            - name: Conda Run pytest
              shell: pwsh
              run: |
                  pytest landbosse/tests

